import type { Metadata } from 'next';
import { Inter, Barlow } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import Navbar from '@/components/navs/navbar';
import Footer from '@/components/navs/footer';

const inter = Inter({ subsets: ['latin'] });
const barlow = Barlow({ subsets: ['latin'], weight:"500", variable: '--font-barlow' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const grotesk = localFont({
  src: '../../public/fonts/NeueHaasDisplayLight.ttf',
  display: 'swap',
  variable: '--font-grotesk',
});
const groteskRoman = localFont({
  src: '../../public/fonts/NeueHaasDisplayRoman.ttf',
  display: 'swap',
  variable: '--font-grotesk-roman',
});
const tobiasRegular = localFont({
  src: '../../public/fonts/tobias-regular.ttf',
  display: 'swap',
  variable: '--font-tobias-regular',
});
const tobiasMedium = localFont({
  src: '../../public/fonts/tobias-medium.ttf',
  display: 'swap',
  variable: '--font-tobias-medium',
});
// const tobiasBold = localFont({
//   src: '../../public/fonts/tobias-bold.ttf',
//   display: 'swap',
//   variable: '--font-tobias-bold',
// });
// const watchWorldRegular = localFont({
//   src: '../../public/fonts/Watchword_regular_demo.otf',
//   display: 'swap',
//   variable: '--font-watchword-regular',
// });
const watchWorldBold = localFont({
  src: '../../public/fonts/Watchword_bold_demo.otf',
  display: 'swap',
  variable: '--font-watchword-bold',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} ${barlow.variable} ${grotesk.variable} ${groteskRoman.variable} ${tobiasRegular.variable} ${watchWorldBold.variable}  ${tobiasMedium.variable}`}
      >
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
